import { BaseLayout } from '@components/layout';
import Head from 'next/head';

const About = () => {
  return (
    <>
      <Head>
        <title>WeatherME ~ About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
    </>
  );
};

About.layout = BaseLayout;
export default About;
