import { BaseLayout } from '@components/layout';
import AboutSection from '@ui/about-section';
import Head from 'next/head';
import { motion } from 'framer-motion';
const About = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Head>
        <title>WeatherME ~ About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <AboutSection />
    </motion.div>
  );
};

About.layout = BaseLayout;
export default About;
