import Head from 'next/head';
import Header from '@ui/header';
import { BaseLayout } from '@components/layout';
import { Container } from '@components/common/container';
import Hero from '@ui/hero';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero />
      </Container>
    </>
  );
};

Home.layout = BaseLayout;

export default Home;
