import Head from 'next/head';
import Header from '@ui/header';
import { BaseLayout } from '@components/layout';
import { Container } from '@components/common/container';
import Hero from '@ui/hero';
import Saves from '@ui/saves';
import Footer from '@ui/footer';
import { motion } from 'framer-motion';
import { useEffect } from 'react';
import Toast from '@components/common/toast';
const Home = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Head>
        <title>WeatherME</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <Container>
        <Hero />
        <Saves />
      </Container>
      <Footer />
    </motion.div>
  );
};

Home.layout = BaseLayout;

export default Home;
